#The sequence of triangle numbers is generated by adding the natural numbers. 
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

#Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# Q: What is the value of the first triangle number to have over five hundred divisors?

def triangle_num(num)
  sum = 0
  (1..num).each { |i| sum += i }
  return sum
end

def factors(num)
  if ( num == 1 )
    return [1]
  end
  
  a = []
  i = 1
  max = num
  while (i < max)
    if ( num % i == 0 ) # i is a factor
      a.push(i)
      
      if ( i != num/i ) # if not square, get the quotient which is a factor as well
        a.push(num/i)
      end
      max = num/i
    end
    i += 1
  end
  
  return a.sort()
end

def num_of_divisors(num)
  i = 1
  while(factors(triangle_num(i)).length < num)
    i += 1
  end
  "Number of divisors: #{triangle_num(i)}"
end

puts num_of_divisors(500)